### ISSUE TITLE
RFE: Multi-Owner signs

### ISSUE THREAD

**Issue by danisaacs** [Phoenix616/ChestShopNotifier#17]
With user shops, allowing >1 user to own a Shop chest would enable simpler shop partnerships.

**Comment by Phoenix616** [comment]
Not saying that it would be impossible to do with the current way shop
signs are handled (via the username on the sign) but definitely difficult
to do.

Maybe via some kind of organization that owns the shop and contains
bultiple players? (That would be best implemented by a seperate plugin
'though)

Also the question would be who should receive/pay the money. All of them in
equal amounts? You would also need some kind of authorization for shops
that buy items so that noone can just steal money from you.

**Comment by Phoenix616** [comment]
Also I just realised that this issue was opened on the ChestShopNotifier repository. This plugin is for transaction notifications, not the main ChestShop repo. I'm closing this here, feel free to open a more detailed issue on the ChestShop repo.
